### ISSUE TITLE
Error - Cannot find native module 'ExpoHttpServer' with Hermes JS Engine

### ISSUE THREAD

**Issue by darbyjack** [simonsturge/expo-http-server#1]
Hi there,

I just came across this library today and was excited to try it out as the old "react-native-http-bridge" doesn't seem maintained or work on Expo applications in general.

I followed the example provided in the README and the following error seems to pop up: "Error: Cannot find native module 'ExpoHttpServer', js engine: hermes"

Environment:
- Framework: Expo (v50.0.17)
- Platform: Android
- Usage: Expo Go (initiated via "expo start")

Full Stacktrace:
![image](https://github.com/simonsturge/expo-http-server/assets/21014720/a0aef90b-4f1c-47e2-80fa-ff3c0db0b4fb)

Hopefully it is just something on my end that I am missing.

(I don't make GitHub issues often but I was excited to test this out so I apologize if anything is missing. Feel free to request more information).

**Comment by simonsturge** [comment]
Hello there

Thanks for trying the package. It's still new so things might not work quite right yet.

I see from your environment that your trying to use Expo Go. This package makes use of custom native modules for interacting with the server. To use the package will require you to create a development build, as the Expo Go client won't have access to those native modules.

**Comment by darbyjack** [comment]
Hey Simon,

That did the trick, thank you!

I'm new to Expo so I'm still learning! Off to go figure out how I can use my own device in development builds instead of an emulator.

Thanks again!
