### ISSUE TITLE
HTTP headers

### ISSUE THREAD

**Issue by Mordo95** [simonsturge/expo-http-server#2]
Hello,

After browsing for a long time to find this functionality in a non-deprecated package I stumbled upon this repository.

Is it possible or planned to be able to send http headers? I'm planning to use this functionality to transfer data from the app back to a website but it needs the access control headers to be set.

I'm not an expert at kotlin or swift, but if I can help I'll be happy to contribute.

Thank you

**Comment by simonsturge** [comment]
Hi there

Nothing planned but that doesn't mean we can't do this if you need it.

What about we add a simple objects, key and value both strings, into the response object? 

```
server.route("/", "GET", async (request) => {
      console.log("Request", "/", "GET", request);
      onServerCalled();
      return {
        statusCode: 200,
        contentType: "application/json",
        headers: {
          "Access-Control-Allow-Origin": "*",
          Connection: "close",
        },
        body: JSON.stringify(obj),
      };
    });
```

Would that work for you?

We could perhaps add some default headers, as it currently does, and then add the custom headers after to provide the option to override the defaults.

**Comment by simonsturge** [comment]
Header option added in [PR#3](https://github.com/simonsturge/expo-http-server/pull/3). I'll merge after doing some testing later.

**Comment by marvinmons55** [comment]
This is perfect and exactly how I had it in mind, thank you!

**Comment by Mordo95** [comment]
This is perfect, exactly how I had it in mind!

**Comment by simonsturge** [comment]
That's good. That's merged so i'll close the ticket now, hope it works for you
